# Generated by Django 4.2.3 on 2024-07-11 03:41

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=254, unique=True)),
                ('color', models.CharField(default='#059669', max_length=7)),
                ('icon', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=254, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('apy', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('due_date', models.DateField(default=accounts.models.current_date, null=True)),
                ('active', models.BooleanField(default=True)),
                ('open_date', models.DateField(default=accounts.models.current_date, null=True)),
                ('next_cycle_date', models.DateField(default=accounts.models.current_date, null=True)),
                ('statement_cycle_length', models.IntegerField(default=0, null=True)),
                ('statement_cycle_period', models.CharField(default='d', max_length=1, null=True)),
                ('rewards_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('last_statement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bank')),
            ],
        ),
    ]
