# Generated by Django 4.2.3 on 2024-07-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rewards_amount',
        ),
    ]
