# Generated by Django 4.2.3 on 2024-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_rewards_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archive_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
