# Generated by Django 4.2.3 on 2024-08-05 14:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_archive_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='apy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='archive_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='due_date',
            field=models.DateField(blank=True, default=accounts.models.current_date, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_statement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='next_cycle_date',
            field=models.DateField(blank=True, default=accounts.models.current_date, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='statement_cycle_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='statement_cycle_period',
            field=models.CharField(blank=True, default='d', max_length=1, null=True),
        ),
    ]
