# Generated by Django 4.2.3 on 2024-08-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_apy_alter_account_archive_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='funding_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_accounts', to='accounts.account'),
        ),
    ]
