# Generated by Django 4.2.3 on 2025-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_funding_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='calcualte_interest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='calculate_payments',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_strategy',
            field=models.CharField(blank=True, default='F', max_length=1, null=True),
        ),
    ]
