# Generated by Django 4.2.3 on 2025-07-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_calcualte_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='calcualte_interest',
        ),
        migrations.AddField(
            model_name='account',
            name='calculate_interest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
