# Generated by Django 4.2.3 on 2025-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_apr_account_annual_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due_day',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='account',
            name='pay_day',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_day',
            field=models.IntegerField(default=15),
        ),
    ]
