# Generated by Django 4.2.3 on 2025-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_due_day_account_pay_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='next_cycle_date',
        ),
    ]
