# Generated by Django 4.2.3 on 2026-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
