# Generated by Django 4.2.3 on 2026-05-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_interest_deposit_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_child_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounts.account'),
        ),
    ]
