# Generated by Django 5.2 on 2026-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_interest_child_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
