from django.db import migrations

BANK_LOGOS = {
    "Ally Financial": "https://icon.horse/icon/ally.com",
    "American Express": "https://icon.horse/icon/americanexpress.com",
    "Ameriprise": "https://icon.horse/icon/ameriprise.com",
    "Ameris Bancorp": "https://icon.horse/icon/amerisbank.com",
    "Arvest Bank": "https://icon.horse/icon/arvest.com",
    "Associated Banc-Corp": "https://icon.horse/icon/associatedbank.com",
    "Atlantic Union Bank": "https://icon.horse/icon/atlanticunionbank.com",
    "Axos Financial": "https://icon.horse/icon/axosbank.com",
    "BMO USA": "https://icon.horse/icon/bmo.com",
    "BNP Paribas": "https://icon.horse/icon/bnpparibas.com",
    "BOK Financial Corporation": "https://icon.horse/icon/bokfinancial.com",
    "Bank of America": "https://icon.horse/icon/bankofamerica.com",
    "Bank of Hawaii": "https://icon.horse/icon/boh.com",
    "BankUnited": "https://icon.horse/icon/bankunited.com",
    "Barclays": "https://icon.horse/icon/barclays.com",
    "Beal Bank": "https://icon.horse/icon/bealbank.com",
    "CIBC Bank USA": "https://icon.horse/icon/cibc.com",
    "Capital One": "https://icon.horse/icon/capitalone.com",
    "Cathay Bank": "https://icon.horse/icon/cathaybank.com",
    "Central Bancompany": "https://icon.horse/icon/centralbank.net",
    "Charles Schwab Corporation": "https://icon.horse/icon/schwab.com",
    "Citigroup": "https://icon.horse/icon/citi.com",
    "Citizens Financial Group": "https://icon.horse/icon/citizensbank.com",
    "Columbia Bank": "https://icon.horse/icon/columbiabank.com",
    "Comerica": "https://icon.horse/icon/comerica.com",
    "Commerce Bancshares": "https://icon.horse/icon/commercebank.com",
    "Credit Suisse": "https://icon.horse/icon/credit-suisse.com",
    "Cullen/Frost Bankers, Inc.": "https://icon.horse/icon/frostbank.com",
    "Customers Bancorp": "https://icon.horse/icon/customersbank.com",
    "Deutsche Bank": "https://icon.horse/icon/db.com",
    "Discover Financial": "https://icon.horse/icon/discover.com",
    "East West Bank": "https://icon.horse/icon/eastwestbank.com",
    "Eastern Bank": "https://icon.horse/icon/easternbank.com",
    "FNB Corporation": "https://icon.horse/icon/fnbcorporation.com",
    "Fifth Third Bank": "https://icon.horse/icon/53.com",
    "First BanCorp": "https://icon.horse/icon/firstbancorp.com",
    "First Citizens BancShares": "https://icon.horse/icon/firstcitizens.com",
    "First Hawaiian Bank": "https://icon.horse/icon/fhb.com",
    "First Horizon National Corporation": "https://icon.horse/icon/firsthorizon.com",
    "First Interstate BancSystem": "https://icon.horse/icon/firstinterstatebank.com",
    "First National of Nebraska": "https://icon.horse/icon/fnni.com",
    "FirstBank Holding Co": "https://icon.horse/icon/efirstbank.com",
    "Fulton Financial Corporation": "https://icon.horse/icon/fultonbank.com",
    "Glacier Bancorp": "https://icon.horse/icon/glacierbancorp.com",
    "Goldman Sachs": "https://icon.horse/icon/goldmansachs.com",
    "HSBC Bank USA": "https://icon.horse/icon/hsbc.com",
    "Hancock Whitney": "https://icon.horse/icon/hancockwhitney.com",
    "Heartland Financial": "https://icon.horse/icon/htlf.com",
    "Home BancShares": "https://icon.horse/icon/homebancshares.com",
    "Hope Bancorp": "https://icon.horse/icon/bankofhope.com",
    "Huntington Bancshares": "https://icon.horse/icon/huntington.com",
    "Independent Bank": "https://icon.horse/icon/independentbank.com",
    "JPMorgan Chase": "https://icon.horse/icon/jpmorganchase.com",
    "John Deere": "https://icon.horse/icon/deere.com",
    "KeyCorp": "https://icon.horse/icon/key.com",
    "M&T Bank": "https://icon.horse/icon/mtb.com",
    "MUFG Americas Holdings Corporation": "https://icon.horse/icon/mufg.jp",
    "MidFirst Bank": "https://icon.horse/icon/midfirst.com",
    "Mizuho Financial Group": "https://icon.horse/icon/mizuhogroup.com",
    "Morgan Stanley": "https://icon.horse/icon/morganstanley.com",
    "New York Community Bank": "https://icon.horse/icon/nycb.com",
    "Northern Trust": "https://icon.horse/icon/northerntrust.com",
    "Old National Bank": "https://icon.horse/icon/oldnational.com",
    "PNC Financial Services": "https://icon.horse/icon/pnc.com",
    "PacWest Bancorp": "https://icon.horse/icon/pacwestbancorp.com",
    "Pacific Premier Bancorp": "https://icon.horse/icon/ppbi.com",
    "Pinnacle Financial Partners": "https://icon.horse/icon/pnfp.com",
    "Popular, Inc.": "https://icon.horse/icon/popular.com",
    "Prosperity Bancshares": "https://icon.horse/icon/prosperitybanktx.com",
    "RBC Bank": "https://icon.horse/icon/rbc.com",
    "Raymond James Financial": "https://icon.horse/icon/raymondjames.com",
    "Regions Financial Corporation": "https://icon.horse/icon/regions.com",
    "Santander Bank": "https://icon.horse/icon/santanderbank.com",
    "Simmons Bank": "https://icon.horse/icon/simmonsbank.com",
    "SoFi": "https://icon.horse/icon/sofi.com",
    "South State Bank": "https://icon.horse/icon/southstatebank.com",
    "State Street Corporation": "https://icon.horse/icon/statestreet.com",
    "Stifel": "https://icon.horse/icon/stifel.com",
    "Sumitomo Mitsui Banking Corporation": "https://icon.horse/icon/smbc.co.jp",
    "Synchrony Financial": "https://icon.horse/icon/synchrony.com",
    "Synovus": "https://icon.horse/icon/synovus.com",
    "TD Bank, N.A.": "https://icon.horse/icon/td.com",
    "TIA": "https://icon.horse/icon/tiaa.org",
    "Texas Capital Bank": "https://icon.horse/icon/texascapitalbank.com",
    "The Bank of New York Mellon": "https://icon.horse/icon/bnymellon.com",
    "Truist Financial": "https://icon.horse/icon/truist.com",
    "U.S. Bancorp": "https://icon.horse/icon/usbank.com",
    "UBS": "https://icon.horse/icon/ubs.com",
    "UMB Financial Corporation": "https://icon.horse/icon/umb.com",
    "USAA": "https://icon.horse/icon/usaa.com",
    "United Bank (West Virginia)": "https://icon.horse/icon/ubsh.com",
    "United Community Bank": "https://icon.horse/icon/ucbi.com",
    "Valley Bank": "https://icon.horse/icon/valley.com",
    "WSFS Bank": "https://icon.horse/icon/wsfsbank.com",
    "Washington Federal": "https://icon.horse/icon/wafd.com",
    "Webster Bank": "https://icon.horse/icon/websterbank.com",
    "Wells Fargo": "https://icon.horse/icon/wellsfargo.com",
    "Western Alliance Bancorporation": "https://icon.horse/icon/westernalliancebancorporation.com",
    "Wintrust Financial": "https://icon.horse/icon/wintrust.com",
}


def populate_logo_urls(apps, schema_editor):
    Bank = apps.get_model("accounts", "Bank")
    for bank_name, logo_url in BANK_LOGOS.items():
        # Set URL if unset, or fix any stale clearbit URLs from a prior migration run
        Bank.objects.filter(bank_name=bank_name).exclude(logo_url=logo_url).update(logo_url=logo_url)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_add_bank_logo_url"),
    ]

    operations = [
        migrations.RunPython(populate_logo_urls, migrations.RunPython.noop),
    ]
