from django.db import migrations

BANK_LOGOS = {
    "Ally Financial": "https://logo.clearbit.com/ally.com",
    "American Express": "https://logo.clearbit.com/americanexpress.com",
    "Ameriprise": "https://logo.clearbit.com/ameriprise.com",
    "Ameris Bancorp": "https://logo.clearbit.com/amerisbank.com",
    "Arvest Bank": "https://logo.clearbit.com/arvest.com",
    "Associated Banc-Corp": "https://logo.clearbit.com/associatedbank.com",
    "Atlantic Union Bank": "https://logo.clearbit.com/atlanticunionbank.com",
    "Axos Financial": "https://logo.clearbit.com/axosbank.com",
    "BMO USA": "https://logo.clearbit.com/bmo.com",
    "BNP Paribas": "https://logo.clearbit.com/bnpparibas.com",
    "BOK Financial Corporation": "https://logo.clearbit.com/bokfinancial.com",
    "Bank of America": "https://logo.clearbit.com/bankofamerica.com",
    "Bank of Hawaii": "https://logo.clearbit.com/boh.com",
    "BankUnited": "https://logo.clearbit.com/bankunited.com",
    "Barclays": "https://logo.clearbit.com/barclays.com",
    "Beal Bank": "https://logo.clearbit.com/bealbank.com",
    "CIBC Bank USA": "https://logo.clearbit.com/cibc.com",
    "Capital One": "https://logo.clearbit.com/capitalone.com",
    "Cathay Bank": "https://logo.clearbit.com/cathaybank.com",
    "Central Bancompany": "https://logo.clearbit.com/centralbank.net",
    "Charles Schwab Corporation": "https://logo.clearbit.com/schwab.com",
    "Citigroup": "https://logo.clearbit.com/citi.com",
    "Citizens Financial Group": "https://logo.clearbit.com/citizensbank.com",
    "Columbia Bank": "https://logo.clearbit.com/columbiabank.com",
    "Comerica": "https://logo.clearbit.com/comerica.com",
    "Commerce Bancshares": "https://logo.clearbit.com/commercebank.com",
    "Credit Suisse": "https://logo.clearbit.com/credit-suisse.com",
    "Cullen/Frost Bankers, Inc.": "https://logo.clearbit.com/frostbank.com",
    "Customers Bancorp": "https://logo.clearbit.com/customersbank.com",
    "Deutsche Bank": "https://logo.clearbit.com/db.com",
    "Discover Financial": "https://logo.clearbit.com/discover.com",
    "East West Bank": "https://logo.clearbit.com/eastwestbank.com",
    "Eastern Bank": "https://logo.clearbit.com/easternbank.com",
    "FNB Corporation": "https://logo.clearbit.com/fnbcorporation.com",
    "Fifth Third Bank": "https://logo.clearbit.com/53.com",
    "First BanCorp": "https://logo.clearbit.com/firstbancorp.com",
    "First Citizens BancShares": "https://logo.clearbit.com/firstcitizens.com",
    "First Hawaiian Bank": "https://logo.clearbit.com/fhb.com",
    "First Horizon National Corporation": "https://logo.clearbit.com/firsthorizon.com",
    "First Interstate BancSystem": "https://logo.clearbit.com/firstinterstatebank.com",
    "First National of Nebraska": "https://logo.clearbit.com/fnni.com",
    "FirstBank Holding Co": "https://logo.clearbit.com/efirstbank.com",
    "Fulton Financial Corporation": "https://logo.clearbit.com/fultonbank.com",
    "Glacier Bancorp": "https://logo.clearbit.com/glacierbancorp.com",
    "Goldman Sachs": "https://logo.clearbit.com/goldmansachs.com",
    "HSBC Bank USA": "https://logo.clearbit.com/hsbc.com",
    "Hancock Whitney": "https://logo.clearbit.com/hancockwhitney.com",
    "Heartland Financial": "https://logo.clearbit.com/htlf.com",
    "Home BancShares": "https://logo.clearbit.com/homebancshares.com",
    "Hope Bancorp": "https://logo.clearbit.com/bankofhope.com",
    "Huntington Bancshares": "https://logo.clearbit.com/huntington.com",
    "Independent Bank": "https://logo.clearbit.com/independentbank.com",
    "JPMorgan Chase": "https://logo.clearbit.com/jpmorganchase.com",
    "John Deere": "https://logo.clearbit.com/deere.com",
    "KeyCorp": "https://logo.clearbit.com/key.com",
    "M&T Bank": "https://logo.clearbit.com/mtb.com",
    "MUFG Americas Holdings Corporation": "https://logo.clearbit.com/mufg.jp",
    "MidFirst Bank": "https://logo.clearbit.com/midfirst.com",
    "Mizuho Financial Group": "https://logo.clearbit.com/mizuhogroup.com",
    "Morgan Stanley": "https://logo.clearbit.com/morganstanley.com",
    "New York Community Bank": "https://logo.clearbit.com/nycb.com",
    "Northern Trust": "https://logo.clearbit.com/northerntrust.com",
    "Old National Bank": "https://logo.clearbit.com/oldnational.com",
    "PNC Financial Services": "https://logo.clearbit.com/pnc.com",
    "PacWest Bancorp": "https://logo.clearbit.com/pacwestbancorp.com",
    "Pacific Premier Bancorp": "https://logo.clearbit.com/ppbi.com",
    "Pinnacle Financial Partners": "https://logo.clearbit.com/pnfp.com",
    "Popular, Inc.": "https://logo.clearbit.com/popular.com",
    "Prosperity Bancshares": "https://logo.clearbit.com/prosperitybanktx.com",
    "RBC Bank": "https://logo.clearbit.com/rbc.com",
    "Raymond James Financial": "https://logo.clearbit.com/raymondjames.com",
    "Regions Financial Corporation": "https://logo.clearbit.com/regions.com",
    "Santander Bank": "https://logo.clearbit.com/santanderbank.com",
    "Simmons Bank": "https://logo.clearbit.com/simmonsbank.com",
    "SoFi": "https://logo.clearbit.com/sofi.com",
    "South State Bank": "https://logo.clearbit.com/southstatebank.com",
    "State Street Corporation": "https://logo.clearbit.com/statestreet.com",
    "Stifel": "https://logo.clearbit.com/stifel.com",
    "Sumitomo Mitsui Banking Corporation": "https://logo.clearbit.com/smbc.co.jp",
    "Synchrony Financial": "https://logo.clearbit.com/synchrony.com",
    "Synovus": "https://logo.clearbit.com/synovus.com",
    "TD Bank, N.A.": "https://logo.clearbit.com/td.com",
    "TIA": "https://logo.clearbit.com/tiaa.org",
    "Texas Capital Bank": "https://logo.clearbit.com/texascapitalbank.com",
    "The Bank of New York Mellon": "https://logo.clearbit.com/bnymellon.com",
    "Truist Financial": "https://logo.clearbit.com/truist.com",
    "U.S. Bancorp": "https://logo.clearbit.com/usbank.com",
    "UBS": "https://logo.clearbit.com/ubs.com",
    "UMB Financial Corporation": "https://logo.clearbit.com/umb.com",
    "USAA": "https://logo.clearbit.com/usaa.com",
    "United Bank (West Virginia)": "https://logo.clearbit.com/ubsh.com",
    "United Community Bank": "https://logo.clearbit.com/ucbi.com",
    "Valley Bank": "https://logo.clearbit.com/valley.com",
    "WSFS Bank": "https://logo.clearbit.com/wsfsbank.com",
    "Washington Federal": "https://logo.clearbit.com/wafd.com",
    "Webster Bank": "https://logo.clearbit.com/websterbank.com",
    "Wells Fargo": "https://logo.clearbit.com/wellsfargo.com",
    "Western Alliance Bancorporation": "https://logo.clearbit.com/westernalliancebancorporation.com",
    "Wintrust Financial": "https://logo.clearbit.com/wintrust.com",
}


def populate_logo_urls(apps, schema_editor):
    Bank = apps.get_model("accounts", "Bank")
    for bank_name, logo_url in BANK_LOGOS.items():
        Bank.objects.filter(bank_name=bank_name, logo_url__isnull=True).update(logo_url=logo_url)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_add_bank_logo_url"),
    ]

    operations = [
        migrations.RunPython(populate_logo_urls, migrations.RunPython.noop),
    ]
