# Generated by Django 5.2 on 2026-05-19 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_account_interest_child_account_and_more'),
        ('tags', '0004_tags_slug_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('TOTALS', 'Totals'), ('COMPARISON', 'Comparison')], max_length=20)),
                ('date_range_type', models.CharField(choices=[('THIS_YEAR', 'This Year'), ('LAST_YEAR', 'Last Year'), ('THIS_QUARTER', 'This Quarter'), ('LAST_QUARTER', 'Last Quarter'), ('TRAILING_12', 'Trailing 12 Months'), ('CUSTOM', 'Custom')], max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('group_by', models.CharField(choices=[('TAG', 'Tag'), ('MONTH', 'Month')], max_length=10)),
                ('show_transactions', models.BooleanField(default=False)),
                ('show_subtotal', models.BooleanField(default=True)),
                ('include_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.maintag')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_selections', to='reports.reportconfig')),
                ('sub_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.subtag')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('main_tag__isnull', True), ('sub_tag__isnull', True), ('tag__isnull', False)), models.Q(('main_tag__isnull', True), ('sub_tag__isnull', False), ('tag__isnull', True)), models.Q(('main_tag__isnull', False), ('sub_tag__isnull', True), ('tag__isnull', True)), _connector='OR'), name='reports_reportconfigtag_exactly_one_set')],
            },
        ),
    ]
