# Generated by Django 5.2 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='period2_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='period2_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
