# Generated by Django 5.2 on 2026-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportconfig_period2_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
