version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - default
    restart: unless-stopped
    ports:
      - 8081:8080
    image: money_frontend:development
    container_name: money_frontend_dev
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - TZ=${TZ}
    command: /bin/sh -c "npm run serve"
    env_file:
      - ./.env.dev
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start.dev.sh
    env_file:
      - ./.env.dev
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - default
    image: money_backend:development
    container_name: money_backend_dev
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start_worker.sh
    env_file:
      - ./.env.dev
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
    depends_on:
      - db
      - backend
    networks:
      - default
    image: money_worker:development
    container_name: money_worker_dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - default
    container_name: money_db_dev
    environment:
      - TZ=${TZ}

volumes:
  postgres_data:
  static_volume:
  media_volume:
