# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import planning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=254, unique=True)),
                ('cap', models.CharField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(max_length=20, unique=True)),
                ('per_paycheck', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('emergency_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('emergency_diff', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=254)),
                ('note_date', models.DateField(default=planning.models.current_date)),
            ],
        ),
        migrations.CreateModel(
            name='ChristmasGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
            ],
        ),
    ]
