# Generated by Django 4.2.3 on 2024-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_ids', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('source_account_id', models.IntegerField()),
                ('destination_account_id', models.IntegerField()),
            ],
        ),
    ]
