# Generated by Django 4.2.3 on 2024-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_calculationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribrule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
