# Generated by Django 4.2.3 on 2024-10-17 20:08

from django.db import migrations, models
import django.db.models.deletion
import planning.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminderexclusion'),
        ('planning', '0003_contribrule_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_ids', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('roll_over', models.BooleanField(default=True)),
                ('start_day', models.DateField(default=planning.models.current_date)),
                ('roll_over_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('Repeat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.repeat')),
            ],
        ),
    ]
