# Generated by Django 4.2.3 on 2024-10-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='Repeat',
            new_name='repeat',
        ),
        migrations.AddField(
            model_name='budget',
            name='widget',
            field=models.BooleanField(default=True),
        ),
    ]
