# Generated by Django 4.2.3 on 2024-10-23 12:40

from django.db import migrations, models
import planning.models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_rename_repeat_budget_repeat_budget_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_start',
            field=models.DateField(default=planning.models.current_date),
        ),
    ]
