# Generated by Django 4.2.3 on 2024-10-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_budget_current_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='current_start',
            new_name='next_start',
        ),
    ]
