# Generated by Django 5.2 on 2026-08-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_account_favorite'),
        ('planning', '0010_detectedrecurring_suggested_fields'),
        ('reminders', '0006_repeat_slug_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contribution',
            name='goal_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='goal_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contribution',
            name='goal_type',
            field=models.CharField(choices=[('none', 'No goal'), ('hold', 'Hold steady'), ('target', 'Reach a target by a date'), ('floor', 'Never dip below a floor'), ('grow', 'Grow by an amount or rate')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='reminder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='reminders.reminder'),
        ),
    ]
