# Generated by Django 5.2 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_contribution_account_contribution_goal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='goal_type',
            field=models.CharField(choices=[('none', 'No goal'), ('hold', 'Cover obligations, hold the buffer'), ('target', 'Reach a target by a date'), ('floor', 'Cover spending, never dip below a floor'), ('grow', 'Grow by an amount or rate'), ('budget', 'Fund a set amount per year'), ('maximise', 'Contribute whatever is left over')], default='none', max_length=10),
        ),
    ]
