# Generated by Django 5.2 on 2026-08-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_contribution_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='minimum_per_paycheck',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
