# Generated by Django 5.2 on 2026-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_contribution_minimum_per_paycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='budgets',
            field=models.ManyToManyField(blank=True, related_name='contributions', to='planning.budget'),
        ),
    ]
