# Generated by Django 5.2 on 2026-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_contribution_one_plan_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='lendable',
            field=models.BooleanField(default=True),
        ),
    ]
