# Generated by Django 5.2 on 2026-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_contribution_lendable'),
        ('tags', '0004_tags_slug_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='sweep_share',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contribution',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contributions', to='tags.tag'),
        ),
    ]
