# Generated by Django 5.2 on 2026-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_contribution_sweep_share_contribution_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='receives_rewards',
            field=models.BooleanField(default=False),
        ),
    ]
