# Generated by Django 5.2 on 2026-08-31 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_contribution_receives_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planning.budget'),
        ),
    ]
