"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
import os
import logging

DEBUG_ENV = os.getenv("DEBUG", "0")  # default to 0 if missing
DB_LOG_LEVEL = logging.DEBUG if DEBUG_ENV == "1" else logging.INFO

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG")))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")


# Application definition

INSTALLED_APPS = [
    "import_export",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "transactions",
    "imports",
    "accounts",
    "tags",
    "reminders",
    "planning",
    "administration",
    "reports",
    "corsheaders",
    "django_filters",
    "dbbackup",
    "ninja",
    "django_q",
    "daphne",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", int(os.environ.get("REDIS_PORT", 6379)))],
            "capacity": 100,
            "expiry": 60,
        },
    }
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS").split(" ")

CORS_ORIGIN_WHITELIST = os.environ.get("CSRF_TRUSTED_ORIGINS").split(" ")

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
DBBACKUP_STORAGE_OPTIONS = {"location": os.environ.get("BACKUP_LOCATION", "/backups/")}
DBBACKUP_CLEANUP_KEEP = 2
DBBACKUP_CLEANUP_KEEP_MEDIA = 2

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # ---------- FORMATTERS ----------
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(message)s",
        },
        "detailed": {
            "format": "[%(asctime)s] %(levelname)s "
            "%(filename)s:%(lineno)d %(funcName)s(): %(message)s",
        },
    },
    # ---------- HANDLERS ----------
    "handlers": {
        "stdout_handler": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "standard",
            "level": "WARNING",
        },
        "db_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "db.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
        "api_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "api.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB, 2 backups (~10MB max)
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
        "error_file_handler": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "error.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,  # 30 days of error history
            "formatter": "detailed",
            "level": DB_LOG_LEVEL,
        },
        "task_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "task.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB, 2 backups (~10MB max)
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
    },
    # ---------- LOGGERS ----------
    "loggers": {
        # Database operations logger
        "db": {
            "handlers": ["db_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        # API activity logger
        "api": {
            "handlers": ["api_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        "error": {
            "handlers": ["error_file_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        "task": {
            "handlers": ["task_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
    },
    # (Optional) fallback root logger
    "root": {
        "handlers": ["stdout_handler"],
        "level": "WARNING",
    },
}

Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 4,
    "timeout": 599,
    "retry": 600,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "max_attempts": 1,
    "label": "Tasks",
    "catch_up": False,
    "poll": 1,
}

UNFOLD = {
    "SITE_TITLE": "LenoreFin",
    "SITE_HEADER": "LenoreFin",
    "SITE_URL": "/",
    "SITE_LOGO": lambda request: static("logov2.png"),
    "SITE_ICON": lambda request: static("favicon.ico"),
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "138 247 213",
            "100": "118 237 200",
            "200": "83 216 176",
            "300": "48 178 138",
            "400": "21 140 104",
            "500": "6 150 106",
            "600": "4 120 84",
            "700": "3 94 66",
            "800": "3 75 53",
            "900": "2 60 42",
            "950": "1 42 29",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Accounts",
                "items": [
                    {"title": "Banks", "link": "/admin/accounts/bank/"},
                    {"title": "Accounts", "link": "/admin/accounts/account/"},
                    {"title": "Account Types", "link": "/admin/accounts/accounttype/"},
                    {"title": "Rewards", "link": "/admin/accounts/reward/"},
                ],
            },
            {
                "title": "Transactions",
                "items": [
                    {"title": "Transactions", "link": "/admin/transactions/transaction/"},
                    {"title": "Paychecks", "link": "/admin/transactions/paycheck/"},
                    {"title": "Transaction Types", "link": "/admin/transactions/transactiontype/"},
                    {"title": "Transaction Statuses", "link": "/admin/transactions/transactionstatus/"},
                    {"title": "Transaction Details", "link": "/admin/transactions/transactiondetail/"},
                    {"title": "Reminder Cache", "link": "/admin/transactions/remindercachetransaction/"},
                    {"title": "Forecast Cache", "link": "/admin/transactions/forecastcachetransaction/"},
                ],
            },
            {
                "title": "Reminders",
                "items": [
                    {"title": "Reminders", "link": "/admin/reminders/reminder/"},
                    {"title": "Repeats", "link": "/admin/reminders/repeat/"},
                    {"title": "Exclusions", "link": "/admin/reminders/reminderexclusion/"},
                ],
            },
            {
                "title": "Tags",
                "items": [
                    {"title": "Tags", "link": "/admin/tags/tag/"},
                    {"title": "Main Tags", "link": "/admin/tags/maintag/"},
                    {"title": "Sub Tags", "link": "/admin/tags/subtag/"},
                    {"title": "Tag Types", "link": "/admin/tags/tagtype/"},
                ],
            },
            {
                "title": "Planning",
                "items": [
                    {"title": "Budgets", "link": "/admin/planning/budget/"},
                    {"title": "Contributions", "link": "/admin/planning/contribution/"},
                    {"title": "Contribution Rules", "link": "/admin/planning/contribrule/"},
                    {"title": "Notes", "link": "/admin/planning/note/"},
                    {"title": "Calculation Rules", "link": "/admin/planning/calculationrule/"},
                    {"title": "Christmas Gifts", "link": "/admin/planning/christmasgift/"},
                ],
            },
            {
                "title": "Administration",
                "items": [
                    {"title": "Options", "link": "/admin/administration/option/"},
                    {"title": "Payees", "link": "/admin/administration/payee/"},
                    {"title": "Version", "link": "/admin/administration/version/"},
                    {"title": "Messages", "link": "/admin/administration/message/"},
                    {"title": "Description History", "link": "/admin/administration/descriptionhistory/"},
                    {"title": "Graph Types", "link": "/admin/administration/graphtype/"},
                ],
            },
            {
                "title": "Users & Groups",
                "items": [
                    {"title": "Users", "link": "/admin/auth/user/"},
                    {"title": "Groups", "link": "/admin/auth/group/"},
                ],
            },
            {
                "title": "Reports",
                "items": [
                    {"title": "Report Configs", "link": "/admin/reports/reportconfig/"},
                ],
            },
            {
                "title": "Imports",
                "items": [
                    {"title": "File Imports", "link": "/admin/imports/fileimport/"},
                    {"title": "Transaction Imports", "link": "/admin/imports/transactionimport/"},
                    {"title": "Import Errors", "link": "/admin/imports/transactionimporterror/"},
                    {"title": "Type Mappings", "link": "/admin/imports/typemapping/"},
                    {"title": "Status Mappings", "link": "/admin/imports/statusmapping/"},
                    {"title": "Account Mappings", "link": "/admin/imports/accountmapping/"},
                    {"title": "Tag Mappings", "link": "/admin/imports/tagmapping/"},
                ],
            },
            {
                "title": "Task Queue",
                "items": [
                    {"title": "Schedules", "link": "/admin/django_q/schedule/"},
                    {"title": "Successful Tasks", "link": "/admin/django_q/success/"},
                    {"title": "Failed Tasks", "link": "/admin/django_q/failure/"},
                    {"title": "Queued Tasks", "link": "/admin/django_q/ormq/"},
                ],
            },
        ],
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


CACHE_TTL = 60 * 60  # 1 hour default
