"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging

DEBUG_ENV = os.getenv("DEBUG", "0")  # default to 0 if missing
DB_LOG_LEVEL = logging.DEBUG if DEBUG_ENV == "1" else logging.INFO

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG")))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")


# Application definition

INSTALLED_APPS = [
    "import_export",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "transactions",
    "imports",
    "accounts",
    "tags",
    "reminders",
    "planning",
    "administration",
    "reports",
    "corsheaders",
    "django_filters",
    "dbbackup",
    "ninja",
    "django_q",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS").split(" ")

CORS_ORIGIN_WHITELIST = os.environ.get("CSRF_TRUSTED_ORIGINS").split(" ")

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
DBBACKUP_STORAGE_OPTIONS = {"location": os.environ.get("BACKUP_LOCATION", "/backups/")}
DBBACKUP_CLEANUP_KEEP = 2
DBBACKUP_CLEANUP_KEEP_MEDIA = 2

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # ---------- FORMATTERS ----------
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(message)s",
        },
        "detailed": {
            "format": "[%(asctime)s] %(levelname)s "
            "%(filename)s:%(lineno)d %(funcName)s(): %(message)s",
        },
    },
    # ---------- HANDLERS ----------
    "handlers": {
        "stdout_handler": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "standard",
            "level": "WARNING",
        },
        "db_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "db.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
        "api_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "api.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB, 2 backups (~10MB max)
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
        "error_file_handler": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "error.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,  # 30 days of error history
            "formatter": "detailed",
            "level": DB_LOG_LEVEL,
        },
        "task_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "task.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5MB, 2 backups (~10MB max)
            "backupCount": 2,
            "formatter": "standard",
            "level": DB_LOG_LEVEL,
        },
    },
    # ---------- LOGGERS ----------
    "loggers": {
        # Database operations logger
        "db": {
            "handlers": ["db_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        # API activity logger
        "api": {
            "handlers": ["api_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        "error": {
            "handlers": ["error_file_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
        "task": {
            "handlers": ["task_file_handler", "stdout_handler"],
            "level": DB_LOG_LEVEL,
            "propagate": False,
        },
    },
    # (Optional) fallback root logger
    "root": {
        "handlers": ["stdout_handler"],
        "level": "WARNING",
    },
}

Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 4,
    "timeout": 599,
    "retry": 600,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "max_attempts": 1,
    "label": "Tasks",
    "catch_up": False,
    "poll": 1,
}

JAZZMIN_SETTINGS = {
    "show_ui_builder": DEBUG,
    "site_title": "LenoreFin",
    "site_header": "LenoreFin",
    "site_brand": "LenoreFin",
    "site_logo": "logov2.png",
    "custom_css": "admin_custom.css",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-fluid",
    "site_icon": "favicon.ico",
    "welcome_sign": "Please log in",
    "copyright": "John Adams",
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Back to Site", "url": "/", "new_window": False},
    ],
    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "Back to Site", "url": "/", "new_window": False},
    ],
    "icons": {
        # Accounts
        "accounts.Bank": "fas fa-landmark",
        "accounts.Account": "fas fa-wallet",
        "accounts.AccountType": "fas fa-layer-group",
        "accounts.Reward": "fas fa-star",
        # Administration
        "administration.Option": "fas fa-sliders-h",
        "administration.Payee": "fas fa-user-tie",
        "administration.Message": "fas fa-envelope",
        "administration.Version": "fas fa-code-branch",
        "administration.DescriptionHistory": "fas fa-history",
        "administration.GraphType": "fas fa-chart-bar",
        # Auth
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Planning
        "planning.Budget": "fas fa-dollar-sign",
        "planning.Contribution": "fas fa-piggy-bank",
        "planning.ContribRule": "fas fa-ruler-combined",
        "planning.Note": "fas fa-sticky-note",
        "planning.CalculationRule": "fas fa-calculator",
        "planning.ChristmasGift": "fas fa-gift",
        # Reminders
        "reminders.Reminder": "fas fa-bell",
        "reminders.Repeat": "fas fa-redo",
        "reminders.ReminderExclusion": "fas fa-bell-slash",
        # Tags
        "tags.TagType": "fas fa-tags",
        "tags.MainTag": "fas fa-tag",
        "tags.SubTag": "fas fa-tag",
        "tags.Tag": "fas fa-tag",
        # Transactions
        "transactions.Transaction": "fas fa-exchange-alt",
        "transactions.Paycheck": "fas fa-money-bill-wave",
        "transactions.TransactionType": "fas fa-list-ul",
        "transactions.TransactionStatus": "fas fa-traffic-light",
        "transactions.TransactionDetail": "fas fa-receipt",
        "transactions.ReminderCacheTransaction": "fas fa-clipboard-list",
        "transactions.ForecastCacheTransaction": "fas fa-chart-line",
        "transactions.ReminderCacheTransactionDetail": "fas fa-clipboard",
        "transactions.ForecastCacheTransactionDetail": "fas fa-chart-area",
        # Reports
        "reports.ReportConfig": "fas fa-chart-pie",
        # Imports
        "imports.FileImport": "fas fa-file-import",
        "imports.TransactionImport": "fas fa-file-alt",
        "imports.TransactionImportTag": "fas fa-tag",
        "imports.TransactionImportError": "fas fa-exclamation-triangle",
        "imports.TypeMapping": "fas fa-random",
        "imports.StatusMapping": "fas fa-random",
        "imports.AccountMapping": "fas fa-random",
        "imports.TagMapping": "fas fa-random",
        # Django Q
        "django_q.Success": "fas fa-check-circle",
        "django_q.Failure": "fas fa-times-circle",
        "django_q.Schedule": "fas fa-clock",
        "django_q.OrmQ": "fas fa-tasks",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-chevron-right",
    "order_with_respect_to": [
        # Accounts
        "accounts",
        "accounts.Bank",
        "accounts.Account",
        "accounts.AccountType",
        "accounts.Reward",
        # Transactions
        "transactions",
        "transactions.Transaction",
        "transactions.Paycheck",
        "transactions.TransactionType",
        "transactions.TransactionStatus",
        "transactions.TransactionDetail",
        "transactions.ReminderCacheTransaction",
        "transactions.ReminderCacheTransactionDetail",
        "transactions.ForecastCacheTransaction",
        "transactions.ForecastCacheTransactionDetail",
        # Reminders
        "reminders",
        "reminders.Reminder",
        "reminders.Repeat",
        "reminders.ReminderExclusion",
        # Tags
        "tags",
        "tags.Tag",
        "tags.MainTag",
        "tags.SubTag",
        "tags.TagType",
        # Planning
        "planning",
        "planning.Budget",
        "planning.Contribution",
        "planning.ContribRule",
        "planning.Note",
        "planning.CalculationRule",
        "planning.ChristmasGift",
        # Administration
        "administration",
        "administration.Option",
        "administration.Payee",
        "administration.Version",
        "administration.Message",
        "administration.DescriptionHistory",
        "administration.GraphType",
        # Auth
        "auth",
        "auth.User",
        "auth.Group",
        # Reports
        "reports",
        "reports.ReportConfig",
        # Imports
        "imports",
        "imports.FileImport",
        "imports.TransactionImport",
        "imports.TransactionImportTag",
        "imports.TransactionImportError",
        "imports.TypeMapping",
        "imports.StatusMapping",
        "imports.AccountMapping",
        "imports.TagMapping",
        # Tasks
        "django_q",
        "django_q.Schedule",
        "django_q.Success",
        "django_q.Failure",
        "django_q.OrmQ",
    ],
    "changeform_format": "collapsible",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-teal",
    "accent": "accent-success",
    "navbar": "navbar-teal navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "minty",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


CACHE_TTL = 60 * 60  # 1 hour default
