# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import imports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to=imports.models.import_file_name)),
                ('processed', models.BooleanField(default=False)),
                ('successful', models.BooleanField(blank=True, default=None, null=True)),
                ('errors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('transaction_type_id', models.IntegerField()),
                ('transaction_status_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('description', models.CharField(max_length=254)),
                ('source_account_id', models.IntegerField()),
                ('destination_account_id', models.IntegerField(default=None, null=True)),
                ('memo', models.CharField(max_length=508)),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.fileimport')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=254)),
                ('type_id', models.IntegerField()),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.fileimport')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=254)),
                ('tag_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('transaction_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.transactionimport')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('status', models.IntegerField()),
                ('transaction_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.transactionimport')),
            ],
        ),
        migrations.CreateModel(
            name='TagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_tag', models.CharField(max_length=254)),
                ('tag_id', models.IntegerField()),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.fileimport')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(max_length=254)),
                ('status_id', models.IntegerField()),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.fileimport')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_account', models.CharField(max_length=254)),
                ('account_id', models.IntegerField()),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.fileimport')),
            ],
        ),
    ]
