# Generated by Django 4.2.3 on 2025-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionimport',
            name='memo',
            field=models.TextField(),
        ),
    ]
