# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_level', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=254)),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('alert_period', models.IntegerField(default=3)),
                ('widget1_graph_name', models.CharField(max_length=254)),
                ('widget1_tag_id', models.IntegerField(blank=True, default=None, null=True)),
                ('widget1_expense', models.BooleanField(default=True)),
                ('widget1_month', models.IntegerField(default=0)),
                ('widget1_exclude', models.CharField(max_length=254)),
                ('widget2_graph_name', models.CharField(max_length=254)),
                ('widget2_tag_id', models.IntegerField(blank=True, default=None, null=True)),
                ('widget2_expense', models.BooleanField(default=True)),
                ('widget2_month', models.IntegerField(default=0)),
                ('widget2_exclude', models.CharField(max_length=254)),
                ('widget3_graph_name', models.CharField(max_length=254)),
                ('widget3_tag_id', models.IntegerField(blank=True, default=None, null=True)),
                ('widget3_expense', models.BooleanField(default=True)),
                ('widget3_month', models.IntegerField(default=0)),
                ('widget3_exclude', models.CharField(max_length=254)),
                ('log_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.errorlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.CharField(max_length=254)),
                ('error_num', models.IntegerField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('error_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.errorlevel')),
            ],
            options={
                'verbose_name_plural': 'Log entries',
            },
        ),
    ]
