# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0001_initial'),
        ('administration', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='reminder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reminders.reminder'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
