# Generated by Django 4.2.3 on 2024-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='archive_length',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='option',
            name='auto_archive',
            field=models.BooleanField(default=True),
        ),
    ]
