# Generated by Django 4.2.3 on 2024-08-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_rename_description_descriptionhistory_description_normalized_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionhistory',
            options={'verbose_name_plural': 'Description histories'},
        ),
    ]
