# Generated by Django 4.2.3 on 2024-08-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_graphtype_remove_option_widget1_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='enable_cc_bill_calculation',
            field=models.BooleanField(default=True),
        ),
    ]
