# Generated by Django 4.2.3 on 2024-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_option_enable_cc_bill_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='report_individual',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='report_main',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
