# Generated by Django 4.2.3 on 2025-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_option_christmas_accounts_option_christmas_rewards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=25),
        ),
    ]
