# Generated by Django 4.2.3 on 2025-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_entry',
            field=models.TextField(),
        ),
    ]
