# Generated by Django 4.2.3 on 2025-12-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_alter_logentry_log_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='error_level',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='option',
            name='log_level',
        ),
        migrations.DeleteModel(
            name='ErrorLevel',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
