# Generated by Django 4.2.3 on 2025-12-15 18:34

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_remove_logentry_account_remove_logentry_error_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(default=administration.models.current_date_time),
        ),
    ]
