# Generated by Django 4.2.3 on 2025-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_message_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionhistory',
            name='description_pretty',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
