# Generated by Django 4.2.3 on 2026-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_readonly_user_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphtype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
