# Generated by Django 5.2 on 2026-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_userdashboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardconfig',
            name='graph_widgets',
            field=models.JSONField(default=list),
        ),
    ]
