# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import reminders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('accounts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_name', models.CharField(max_length=254, unique=True)),
                ('days', models.IntegerField(default=0)),
                ('weeks', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('years', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.CharField(max_length=254)),
                ('start_date', models.DateField(default=reminders.models.current_date)),
                ('next_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('auto_add', models.BooleanField(default=False)),
                ('reminder_destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_destination_account', to='accounts.account')),
                ('reminder_source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_source_account', to='accounts.account')),
                ('repeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.repeat')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype')),
            ],
        ),
    ]
