# Generated by Django 4.2.3 on 2024-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='memo',
            field=models.CharField(blank=True, default=None, max_length=508, null=True),
        ),
    ]
