# Generated by Django 4.2.3 on 2024-07-18 13:28

from django.db import migrations, models
import django.db.models.deletion
import reminders.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_date', models.DateField(default=reminders.models.current_date)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.reminder')),
            ],
        ),
    ]
