# Generated by Django 4.2.3 on 2026-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repeat',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
            preserve_default=False,
        ),
    ]
