# Generated by Django 4.2.3 on 2024-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('tags', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('health', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fsa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dca', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('union_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('four_fifty_seven_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.payee')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=transactions.models.current_date)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('memo', models.CharField(blank=True, default=None, max_length=508, null=True)),
                ('description', models.CharField(max_length=254)),
                ('edit_date', models.DateField(default=transactions.models.current_date)),
                ('add_date', models.DateField(default=transactions.models.current_date)),
                ('checkNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('destination_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='accounts.account')),
                ('paycheck', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.paycheck')),
                ('source_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_status', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction statuses',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=transactions.models.transaction_image_name)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactionstatus'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype'),
        ),
    ]
