# Generated by Django 4.2.3 on 2024-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='full_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
