# Generated by Django 4.2.3 on 2025-11-25 02:46

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('reminders', '0004_alter_reminder_memo'),
        ('accounts', '0010_remove_account_apr_account_annual_rate'),
        ('transactions', '0004_forecasttransactioncache_remindertransactioncache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCacheTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=transactions.models.current_date)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('memo', models.TextField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=254)),
                ('edit_date', models.DateField(default=transactions.models.current_date)),
                ('add_date', models.DateField(default=transactions.models.current_date)),
                ('checkNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('destination_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_cache_destination_transactions', to='accounts.account')),
                ('paycheck', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.paycheck')),
                ('source_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_cache_source_transactions', to='accounts.account')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactionstatus')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastCacheTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('full_toggle', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.forecastcachetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderCacheTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=transactions.models.current_date)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('memo', models.TextField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=254)),
                ('edit_date', models.DateField(default=transactions.models.current_date)),
                ('add_date', models.DateField(default=transactions.models.current_date)),
                ('checkNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('destination_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_cache_destination_transactions', to='accounts.account')),
                ('paycheck', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.paycheck')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.reminder')),
                ('source_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_cache_source_transactions', to='accounts.account')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactionstatus')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderCacheTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('full_toggle', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.remindercachetransaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='forecasttransactioncachetransactiondetail',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='forecasttransactioncachetransactiondetail',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='destination_account',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='paycheck',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='status',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncache',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncachetransactiondetail',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='remindertransactioncachetransactiondetail',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='ForecastTransactionCache',
        ),
        migrations.DeleteModel(
            name='ForecastTransactionCacheTransactionDetail',
        ),
        migrations.DeleteModel(
            name='ReminderTransactionCache',
        ),
        migrations.DeleteModel(
            name='ReminderTransactionCacheTransactionDetail',
        ),
    ]
