# Generated by Django 4.2.3 on 2025-12-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_due_date_and_more'),
        ('transactions', '0005_forecastcachetransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='accounts.account'),
        ),
    ]
