# Generated by Django 4.2.3 on 2025-12-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_due_date_and_more'),
        ('transactions', '0007_alter_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastcachetransaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_cache_destination_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='forecastcachetransaction',
            name='source_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_cache_source_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='remindercachetransaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_cache_destination_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='remindercachetransaction',
            name='source_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_cache_source_transactions', to='accounts.account'),
        ),
    ]
