# Generated by Django 4.2.3 on 2026-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_forecastcachetransaction_destination_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
