<template>
  <v-container>
    <v-row class="pa-1 ga-1" no-gutters>
      <v-col class="rounded text-center">
        <v-tabs v-model="main_tab" color="accent">
          <v-tab
            v-for="(main, index) in expenses"
            :key="index"
            :value="main.title"
            >{{ main.title }}</v-tab
          >
        </v-tabs>
        <v-window v-model="main_tab">
          <v-window-item
            v-for="(main_window, main_index) in expenses"
            :key="main_index"
            :value="main_window.title"
          >
            <v-tabs v-model="tab[main_index]" color="accent">
              <v-tab
                v-for="(sub_window, sub_index) in main_window.data"
                :key="sub_index"
                :value="sub_window.key_name"
                >{{ sub_window.pretty_name }}</v-tab
              >
            </v-tabs>
            <v-window v-model="tab[main_index]">
              <v-window-item
                v-for="(sub_window, sub_index) in main_window.data"
                :key="sub_index"
                :value="sub_window.key_name"
              >
                <ReportGraphWidget
                  :data="sub_window"
                  :graphName="sub_window.pretty_name"
                  :key="sub_index"
                  :isLoading="isLoading"
              /></v-window-item>
              <ReportTableWidget
                :isLoading="isLoading"
                :data="main_window.data"
            /></v-window>
          </v-window-item>
        </v-window> </v-col
    ></v-row>
  </v-container>
</template>
<script setup>
import { ref } from "vue";
import ReportGraphWidget from "@/components/ReportGraphWidget.vue";
import ReportTableWidget from "@/components/ReportTableWidget.vue";

const main_tab = ref(0);
const isLoading = ref(false);
const expenses = ref([
  {
    title: "Main",
    data: [
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Housing",
        key_name: "housing",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "car",
        key_name: "Car",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Debt",
        key_name: "debt",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Groceries",
        key_name: "groceries",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Subscriptions",
        key_name: "subscriptions",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "FSA",
        key_name: "fsa",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "MoneyPile",
        key_name: "money_pile",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Reno",
        key_name: "reno",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "vacation",
        key_name: "vacation",
      },
    ],
  },
  {
    title: "Money Pile",
    data: [
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Housing",
        key_name: "housing",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "car",
        key_name: "Car",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Debt",
        key_name: "debt",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Groceries",
        key_name: "groceries",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Subscriptions",
        key_name: "subscriptions",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "FSA",
        key_name: "fsa",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "MoneyPile",
        key_name: "money_pile",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "Reno",
        key_name: "reno",
      },
      {
        data: {
          labels: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          datasets: [
            {
              borderColor: null,
              backgroundColor: "#046959",
              tension: null,
              data: [
                "100",
                "100",
                "100",
                "200",
                "300",
                "300",
                "200",
                "100",
                "200",
                "300",
                "300",
                "400",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2024",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
            {
              borderColor: null,
              backgroundColor: "#c2fff5",
              tension: null,
              data: [
                "100",
                "200",
                "200",
                "200",
                "300",
                "400",
                "500",
                "100",
                "200",
                "100",
                "200",
                "250",
              ],
              fill: null,
              pointStyle: null,
              radius: null,
              hitRadius: null,
              hoverRadius: null,
              label: "2023",
              hoverBackgroundColor: "rgba(75,192,192,0.6)",
              hoverBorderColor: "rgba(75,192,192,1)",
            },
          ],
        },
        year1: 2024,
        year2: 2023,
        year1_avg: "150.0",
        year2_avg: "200.0",
        pretty_name: "vacation",
        key_name: "vacation",
      },
    ],
  },
]);

const tab = ref(Array(expenses.value.length).fill(0));
</script>
