<template>
  <v-container>
    <v-row class="pa-1 ga-1" no-gutters>
      <v-col class="rounded text-center">
        <v-tabs v-model="tab" color="accent">
          <v-tab value="gross" density="compact">Gross</v-tab>
          <v-tab value="net" density="compact">Net</v-tab>
          <v-tab value="taxes" density="compact">Taxes</v-tab>
          <v-tab value="health" density="compact">Health</v-tab>
          <v-tab value="pension" density="compact">Pension</v-tab>
          <v-tab value="fsa" density="compact">FSA</v-tab>
          <v-tab value="dca" density="compact">DCA</v-tab>
          <v-tab value="union" density="compact">Union Dues</v-tab>
          <v-tab value="457b" density="compact">457B</v-tab>
        </v-tabs>
        <v-window v-model="tab">
          <v-window-item value="gross"
            ><ReportGraphWidget
              :data="pay.gross"
              graphName="Gross"
              key="gross" /></v-window-item
          ><v-window-item value="net"
            ><ReportGraphWidget :data="pay.net" graphName="Net" key="net"
          /></v-window-item>
          <v-window-item value="taxes"
            ><ReportGraphWidget :data="pay.taxes" graphName="Taxes" key="taxes"
          /></v-window-item>
          <v-window-item value="health"
            ><ReportGraphWidget
              :data="pay.health"
              graphName="Health"
              key="health"
          /></v-window-item>
          <v-window-item value="pension"
            ><ReportGraphWidget
              :data="pay.pension"
              graphName="Pension"
              key="pension"
          /></v-window-item>
          <v-window-item value="fsa"
            ><ReportGraphWidget :data="pay.fsa" graphName="FSA" key="fsa"
          /></v-window-item>
          <v-window-item value="dca"
            ><ReportGraphWidget :data="pay.dca" graphName="DCA" key="dca"
          /></v-window-item>
          <v-window-item value="union"
            ><ReportGraphWidget
              :data="pay.union"
              graphName="Union Dues"
              key="union"
          /></v-window-item>
          <v-window-item value="457b"
            ><ReportGraphWidget
              :data="pay.fourfiftysevenb"
              graphName="457B"
              key="457b" /></v-window-item></v-window></v-col></v-row
  ></v-container>
</template>
<script setup>
import { ref } from "vue";
import ReportGraphWidget from "@/components/ReportGraphWidget.vue";

const tab = ref(0); // Tab model
const pay = ref({
  gross: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  net: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  taxes: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  health: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  pension: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  fsa: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  dca: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  union: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
  fourfiftysevenb: {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
  },
});
</script>
