<template>
  <v-container>
    <v-row class="pa-1 ga-1" no-gutters>
      <v-col class="rounded text-center">
        <v-tabs v-model="tab" color="accent">
          <v-tab
            v-for="(item, index) in pay"
            :key="index"
            :value="item.key_name"
            >{{ item.pretty_name }}</v-tab
          >
        </v-tabs>
        <v-window v-model="tab">
          <v-window-item
            v-for="(item, index) in pay"
            :key="index"
            :value="item.key_name"
          >
            <ReportGraphWidget
              :data="item"
              :graphName="item.pretty_name"
              :key="index"
              :isLoading="
                isLoading
              " /></v-window-item></v-window></v-col></v-row
    ><v-row class="pa-1 ga-1" no-gutters>
      <v-col class="rounded text-center"
        ><ReportTableWidget :isLoading="isLoading" :data="pay" /></v-col
    ></v-row>
  </v-container>
</template>
<script setup>
import { ref } from "vue";
import ReportGraphWidget from "@/components/ReportGraphWidget.vue";
import ReportTableWidget from "@/components/ReportTableWidget.vue";

const tab = ref(0); // Tab model
const isLoading = ref(false);
const pay = ref([
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Gross",
    key_name: "gross",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Net",
    key_name: "net",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Taxes",
    key_name: "taxes",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Health",
    key_name: "health",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Pension",
    key_name: "pension",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "FSA",
    key_name: "fsa",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "DCA",
    key_name: "dca",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "Union Dues",
    key_name: "union",
  },
  {
    data: {
      labels: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
      datasets: [
        {
          borderColor: null,
          backgroundColor: "#046959",
          tension: null,
          data: [
            "100",
            "100",
            "100",
            "200",
            "300",
            "300",
            "200",
            "100",
            "200",
            "300",
            "300",
            "400",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2024",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
        {
          borderColor: null,
          backgroundColor: "#c2fff5",
          tension: null,
          data: [
            "100",
            "200",
            "200",
            "200",
            "300",
            "400",
            "500",
            "100",
            "200",
            "100",
            "200",
            "250",
          ],
          fill: null,
          pointStyle: null,
          radius: null,
          hitRadius: null,
          hoverRadius: null,
          label: "2023",
          hoverBackgroundColor: "rgba(75,192,192,0.6)",
          hoverBorderColor: "rgba(75,192,192,1)",
        },
      ],
    },
    year1: 2024,
    year2: 2023,
    year1_avg: "150.0",
    year2_avg: "200.0",
    pretty_name: "457B",
    key_name: "fourfiftysevenb",
  },
]);
</script>
