name: Post to Reddit

on:
  release:
    types: [published]  # Triggers when a release is published (not a draft or prerelease)

jobs:
  reddit:
    if: github.event.release.prerelease == false  # Only run for final releases
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Extract release type from tag
        id: tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Full tag: $TAG"

          # Parse tag version (e.g., 1.2.3 or 1.2.3-rc.1)
          MAJOR=$(echo "$TAG" | cut -d. -f1)
          MINOR=$(echo "$TAG" | cut -d. -f2)
          PATCH=$(echo "$TAG" | cut -d. -f3 | cut -d- -f1)

          echo "Parsed Version: MAJOR=$MAJOR, MINOR=$MINOR, PATCH=$PATCH"

          # Determine release type
          if [ "$PATCH" = "0" ]; then
            echo "type=minor" >> "$GITHUB_OUTPUT"
          else
            echo "type=patch" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip non-minor/major releases
        if: steps.tag.outputs.type != 'minor'
        run: |
          echo "Not a minor or major release. Skipping Reddit post."
          exit 0

      - name: Get release notes
        id: release_notes
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name
            });
            return release.data.body || "No changelog found.";

      - name: Post to Reddit
        env:
          COMMIT_TAG: ${{ github.event.release.tag_name }}
          RELEASE_NOTES: ${{ steps.release_notes.outputs.result }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python scripts/post_to_reddit.py
